package grpc;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hotel.proto

public final class Hotel {
  private Hotel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code RoomType}
   */
  public enum RoomType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BASIQUE = 0;</code>
     */
    BASIQUE(0),
    /**
     * <code>MIDL_GAMME = 1;</code>
     */
    MIDL_GAMME(1),
    /**
     * <code>HAUT_GAMME = 2;</code>
     */
    HAUT_GAMME(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>BASIQUE = 0;</code>
     */
    public static final int BASIQUE_VALUE = 0;
    /**
     * <code>MIDL_GAMME = 1;</code>
     */
    public static final int MIDL_GAMME_VALUE = 1;
    /**
     * <code>HAUT_GAMME = 2;</code>
     */
    public static final int HAUT_GAMME_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static RoomType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RoomType forNumber(int value) {
      switch (value) {
        case 0: return BASIQUE;
        case 1: return MIDL_GAMME;
        case 2: return HAUT_GAMME;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RoomType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RoomType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RoomType>() {
            public RoomType findValueByNumber(int number) {
              return RoomType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Hotel.getDescriptor().getEnumTypes().get(0);
    }

    private static final RoomType[] VALUES = values();

    public static RoomType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RoomType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RoomType)
  }

  public interface RoomDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RoomData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RoomType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.RoomType type = 1;</code>
     * @return The type.
     */
    RoomType getType();

    /**
     * <code>float price = 2;</code>
     * @return The price.
     */
    float getPrice();
  }
  /**
   * Protobuf type {@code RoomData}
   */
  public static final class RoomData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RoomData)
      RoomDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoomData.newBuilder() to construct.
    private RoomData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoomData() {
      type_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RoomData();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoomData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 21: {

              price_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Hotel.internal_static_RoomData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Hotel.internal_static_RoomData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RoomData.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.RoomType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.RoomType type = 1;</code>
     * @return The type.
     */
    @Override public RoomType getType() {
      @SuppressWarnings("deprecation")
      RoomType result = RoomType.valueOf(type_);
      return result == null ? RoomType.UNRECOGNIZED : result;
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    private float price_;
    /**
     * <code>float price = 2;</code>
     * @return The price.
     */
    @Override
    public float getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != RoomType.BASIQUE.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (price_ != 0F) {
        output.writeFloat(2, price_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != RoomType.BASIQUE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (price_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RoomData)) {
        return super.equals(obj);
      }
      RoomData other = (RoomData) obj;

      if (type_ != other.type_) return false;
      if (Float.floatToIntBits(getPrice())
          != Float.floatToIntBits(
              other.getPrice())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getPrice());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RoomData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoomData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoomData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoomData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoomData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoomData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoomData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RoomData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RoomData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RoomData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RoomData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RoomData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RoomData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RoomData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RoomData)
        RoomDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Hotel.internal_static_RoomData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Hotel.internal_static_RoomData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RoomData.class, Builder.class);
      }

      // Construct using Hotel.RoomData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        price_ = 0F;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Hotel.internal_static_RoomData_descriptor;
      }

      @Override
      public RoomData getDefaultInstanceForType() {
        return RoomData.getDefaultInstance();
      }

      @Override
      public RoomData build() {
        RoomData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RoomData buildPartial() {
        RoomData result = new RoomData(this);
        result.type_ = type_;
        result.price_ = price_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RoomData) {
          return mergeFrom((RoomData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RoomData other) {
        if (other == RoomData.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getPrice() != 0F) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RoomData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RoomData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.RoomType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.RoomType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RoomType type = 1;</code>
       * @return The type.
       */
      @Override
      public RoomType getType() {
        @SuppressWarnings("deprecation")
        RoomType result = RoomType.valueOf(type_);
        return result == null ? RoomType.UNRECOGNIZED : result;
      }
      /**
       * <code>.RoomType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(RoomType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RoomType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private float price_ ;
      /**
       * <code>float price = 2;</code>
       * @return The price.
       */
      @Override
      public float getPrice() {
        return price_;
      }
      /**
       * <code>float price = 2;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(float value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float price = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        
        price_ = 0F;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RoomData)
    }

    // @@protoc_insertion_point(class_scope:RoomData)
    private static final RoomData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RoomData();
    }

    public static RoomData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomData>
        PARSER = new com.google.protobuf.AbstractParser<RoomData>() {
      @Override
      public RoomData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoomData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoomData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RoomData> getParserForType() {
      return PARSER;
    }

    @Override
    public RoomData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DatesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Dates)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp debut = 1;</code>
     * @return Whether the debut field is set.
     */
    boolean hasDebut();
    /**
     * <code>.google.protobuf.Timestamp debut = 1;</code>
     * @return The debut.
     */
    com.google.protobuf.Timestamp getDebut();
    /**
     * <code>.google.protobuf.Timestamp debut = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDebutOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp fin = 2;</code>
     * @return Whether the fin field is set.
     */
    boolean hasFin();
    /**
     * <code>.google.protobuf.Timestamp fin = 2;</code>
     * @return The fin.
     */
    com.google.protobuf.Timestamp getFin();
    /**
     * <code>.google.protobuf.Timestamp fin = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getFinOrBuilder();
  }
  /**
   * Protobuf type {@code Dates}
   */
  public static final class Dates extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Dates)
      DatesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Dates.newBuilder() to construct.
    private Dates(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dates() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Dates();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Dates(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (debut_ != null) {
                subBuilder = debut_.toBuilder();
              }
              debut_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(debut_);
                debut_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (fin_ != null) {
                subBuilder = fin_.toBuilder();
              }
              fin_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fin_);
                fin_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Hotel.internal_static_Dates_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Hotel.internal_static_Dates_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Dates.class, Builder.class);
    }

    public static final int DEBUT_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp debut_;
    /**
     * <code>.google.protobuf.Timestamp debut = 1;</code>
     * @return Whether the debut field is set.
     */
    @Override
    public boolean hasDebut() {
      return debut_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp debut = 1;</code>
     * @return The debut.
     */
    @Override
    public com.google.protobuf.Timestamp getDebut() {
      return debut_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : debut_;
    }
    /**
     * <code>.google.protobuf.Timestamp debut = 1;</code>
     */
    @Override
    public com.google.protobuf.TimestampOrBuilder getDebutOrBuilder() {
      return getDebut();
    }

    public static final int FIN_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp fin_;
    /**
     * <code>.google.protobuf.Timestamp fin = 2;</code>
     * @return Whether the fin field is set.
     */
    @Override
    public boolean hasFin() {
      return fin_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp fin = 2;</code>
     * @return The fin.
     */
    @Override
    public com.google.protobuf.Timestamp getFin() {
      return fin_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : fin_;
    }
    /**
     * <code>.google.protobuf.Timestamp fin = 2;</code>
     */
    @Override
    public com.google.protobuf.TimestampOrBuilder getFinOrBuilder() {
      return getFin();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (debut_ != null) {
        output.writeMessage(1, getDebut());
      }
      if (fin_ != null) {
        output.writeMessage(2, getFin());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (debut_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDebut());
      }
      if (fin_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFin());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Dates)) {
        return super.equals(obj);
      }
      Dates other = (Dates) obj;

      if (hasDebut() != other.hasDebut()) return false;
      if (hasDebut()) {
        if (!getDebut()
            .equals(other.getDebut())) return false;
      }
      if (hasFin() != other.hasFin()) return false;
      if (hasFin()) {
        if (!getFin()
            .equals(other.getFin())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDebut()) {
        hash = (37 * hash) + DEBUT_FIELD_NUMBER;
        hash = (53 * hash) + getDebut().hashCode();
      }
      if (hasFin()) {
        hash = (37 * hash) + FIN_FIELD_NUMBER;
        hash = (53 * hash) + getFin().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Dates parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dates parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dates parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dates parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dates parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dates parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dates parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Dates parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Dates parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Dates parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Dates parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Dates parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Dates prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Dates}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Dates)
        DatesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Hotel.internal_static_Dates_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Hotel.internal_static_Dates_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Dates.class, Builder.class);
      }

      // Construct using Hotel.Dates.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (debutBuilder_ == null) {
          debut_ = null;
        } else {
          debut_ = null;
          debutBuilder_ = null;
        }
        if (finBuilder_ == null) {
          fin_ = null;
        } else {
          fin_ = null;
          finBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Hotel.internal_static_Dates_descriptor;
      }

      @Override
      public Dates getDefaultInstanceForType() {
        return Dates.getDefaultInstance();
      }

      @Override
      public Dates build() {
        Dates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Dates buildPartial() {
        Dates result = new Dates(this);
        if (debutBuilder_ == null) {
          result.debut_ = debut_;
        } else {
          result.debut_ = debutBuilder_.build();
        }
        if (finBuilder_ == null) {
          result.fin_ = fin_;
        } else {
          result.fin_ = finBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Dates) {
          return mergeFrom((Dates)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Dates other) {
        if (other == Dates.getDefaultInstance()) return this;
        if (other.hasDebut()) {
          mergeDebut(other.getDebut());
        }
        if (other.hasFin()) {
          mergeFin(other.getFin());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Dates parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Dates) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Timestamp debut_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> debutBuilder_;
      /**
       * <code>.google.protobuf.Timestamp debut = 1;</code>
       * @return Whether the debut field is set.
       */
      public boolean hasDebut() {
        return debutBuilder_ != null || debut_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 1;</code>
       * @return The debut.
       */
      public com.google.protobuf.Timestamp getDebut() {
        if (debutBuilder_ == null) {
          return debut_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : debut_;
        } else {
          return debutBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 1;</code>
       */
      public Builder setDebut(com.google.protobuf.Timestamp value) {
        if (debutBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          debut_ = value;
          onChanged();
        } else {
          debutBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 1;</code>
       */
      public Builder setDebut(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (debutBuilder_ == null) {
          debut_ = builderForValue.build();
          onChanged();
        } else {
          debutBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 1;</code>
       */
      public Builder mergeDebut(com.google.protobuf.Timestamp value) {
        if (debutBuilder_ == null) {
          if (debut_ != null) {
            debut_ =
              com.google.protobuf.Timestamp.newBuilder(debut_).mergeFrom(value).buildPartial();
          } else {
            debut_ = value;
          }
          onChanged();
        } else {
          debutBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 1;</code>
       */
      public Builder clearDebut() {
        if (debutBuilder_ == null) {
          debut_ = null;
          onChanged();
        } else {
          debut_ = null;
          debutBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDebutBuilder() {
        
        onChanged();
        return getDebutFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDebutOrBuilder() {
        if (debutBuilder_ != null) {
          return debutBuilder_.getMessageOrBuilder();
        } else {
          return debut_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : debut_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDebutFieldBuilder() {
        if (debutBuilder_ == null) {
          debutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDebut(),
                  getParentForChildren(),
                  isClean());
          debut_ = null;
        }
        return debutBuilder_;
      }

      private com.google.protobuf.Timestamp fin_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> finBuilder_;
      /**
       * <code>.google.protobuf.Timestamp fin = 2;</code>
       * @return Whether the fin field is set.
       */
      public boolean hasFin() {
        return finBuilder_ != null || fin_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 2;</code>
       * @return The fin.
       */
      public com.google.protobuf.Timestamp getFin() {
        if (finBuilder_ == null) {
          return fin_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : fin_;
        } else {
          return finBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 2;</code>
       */
      public Builder setFin(com.google.protobuf.Timestamp value) {
        if (finBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fin_ = value;
          onChanged();
        } else {
          finBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 2;</code>
       */
      public Builder setFin(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (finBuilder_ == null) {
          fin_ = builderForValue.build();
          onChanged();
        } else {
          finBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 2;</code>
       */
      public Builder mergeFin(com.google.protobuf.Timestamp value) {
        if (finBuilder_ == null) {
          if (fin_ != null) {
            fin_ =
              com.google.protobuf.Timestamp.newBuilder(fin_).mergeFrom(value).buildPartial();
          } else {
            fin_ = value;
          }
          onChanged();
        } else {
          finBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 2;</code>
       */
      public Builder clearFin() {
        if (finBuilder_ == null) {
          fin_ = null;
          onChanged();
        } else {
          fin_ = null;
          finBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getFinBuilder() {
        
        onChanged();
        return getFinFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getFinOrBuilder() {
        if (finBuilder_ != null) {
          return finBuilder_.getMessageOrBuilder();
        } else {
          return fin_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : fin_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getFinFieldBuilder() {
        if (finBuilder_ == null) {
          finBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getFin(),
                  getParentForChildren(),
                  isClean());
          fin_ = null;
        }
        return finBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Dates)
    }

    // @@protoc_insertion_point(class_scope:Dates)
    private static final Dates DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Dates();
    }

    public static Dates getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Dates>
        PARSER = new com.google.protobuf.AbstractParser<Dates>() {
      @Override
      public Dates parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Dates(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dates> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Dates> getParserForType() {
      return PARSER;
    }

    @Override
    public Dates getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BookingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Booking)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RoomType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.RoomType type = 1;</code>
     * @return The type.
     */
    RoomType getType();

    /**
     * <code>.google.protobuf.Timestamp debut = 2;</code>
     * @return Whether the debut field is set.
     */
    boolean hasDebut();
    /**
     * <code>.google.protobuf.Timestamp debut = 2;</code>
     * @return The debut.
     */
    com.google.protobuf.Timestamp getDebut();
    /**
     * <code>.google.protobuf.Timestamp debut = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDebutOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp fin = 3;</code>
     * @return Whether the fin field is set.
     */
    boolean hasFin();
    /**
     * <code>.google.protobuf.Timestamp fin = 3;</code>
     * @return The fin.
     */
    com.google.protobuf.Timestamp getFin();
    /**
     * <code>.google.protobuf.Timestamp fin = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getFinOrBuilder();
  }
  /**
   * Protobuf type {@code Booking}
   */
  public static final class Booking extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Booking)
      BookingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Booking.newBuilder() to construct.
    private Booking(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Booking() {
      type_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Booking();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Booking(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (debut_ != null) {
                subBuilder = debut_.toBuilder();
              }
              debut_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(debut_);
                debut_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (fin_ != null) {
                subBuilder = fin_.toBuilder();
              }
              fin_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fin_);
                fin_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Hotel.internal_static_Booking_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Hotel.internal_static_Booking_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Booking.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.RoomType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.RoomType type = 1;</code>
     * @return The type.
     */
    @Override public RoomType getType() {
      @SuppressWarnings("deprecation")
      RoomType result = RoomType.valueOf(type_);
      return result == null ? RoomType.UNRECOGNIZED : result;
    }

    public static final int DEBUT_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp debut_;
    /**
     * <code>.google.protobuf.Timestamp debut = 2;</code>
     * @return Whether the debut field is set.
     */
    @Override
    public boolean hasDebut() {
      return debut_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp debut = 2;</code>
     * @return The debut.
     */
    @Override
    public com.google.protobuf.Timestamp getDebut() {
      return debut_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : debut_;
    }
    /**
     * <code>.google.protobuf.Timestamp debut = 2;</code>
     */
    @Override
    public com.google.protobuf.TimestampOrBuilder getDebutOrBuilder() {
      return getDebut();
    }

    public static final int FIN_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp fin_;
    /**
     * <code>.google.protobuf.Timestamp fin = 3;</code>
     * @return Whether the fin field is set.
     */
    @Override
    public boolean hasFin() {
      return fin_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp fin = 3;</code>
     * @return The fin.
     */
    @Override
    public com.google.protobuf.Timestamp getFin() {
      return fin_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : fin_;
    }
    /**
     * <code>.google.protobuf.Timestamp fin = 3;</code>
     */
    @Override
    public com.google.protobuf.TimestampOrBuilder getFinOrBuilder() {
      return getFin();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != RoomType.BASIQUE.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (debut_ != null) {
        output.writeMessage(2, getDebut());
      }
      if (fin_ != null) {
        output.writeMessage(3, getFin());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != RoomType.BASIQUE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (debut_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDebut());
      }
      if (fin_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getFin());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Booking)) {
        return super.equals(obj);
      }
      Booking other = (Booking) obj;

      if (type_ != other.type_) return false;
      if (hasDebut() != other.hasDebut()) return false;
      if (hasDebut()) {
        if (!getDebut()
            .equals(other.getDebut())) return false;
      }
      if (hasFin() != other.hasFin()) return false;
      if (hasFin()) {
        if (!getFin()
            .equals(other.getFin())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasDebut()) {
        hash = (37 * hash) + DEBUT_FIELD_NUMBER;
        hash = (53 * hash) + getDebut().hashCode();
      }
      if (hasFin()) {
        hash = (37 * hash) + FIN_FIELD_NUMBER;
        hash = (53 * hash) + getFin().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Booking parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Booking parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Booking parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Booking parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Booking parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Booking parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Booking parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Booking parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Booking parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Booking parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Booking parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Booking parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Booking prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Booking}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Booking)
        BookingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Hotel.internal_static_Booking_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Hotel.internal_static_Booking_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Booking.class, Builder.class);
      }

      // Construct using Hotel.Booking.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (debutBuilder_ == null) {
          debut_ = null;
        } else {
          debut_ = null;
          debutBuilder_ = null;
        }
        if (finBuilder_ == null) {
          fin_ = null;
        } else {
          fin_ = null;
          finBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Hotel.internal_static_Booking_descriptor;
      }

      @Override
      public Booking getDefaultInstanceForType() {
        return Booking.getDefaultInstance();
      }

      @Override
      public Booking build() {
        Booking result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Booking buildPartial() {
        Booking result = new Booking(this);
        result.type_ = type_;
        if (debutBuilder_ == null) {
          result.debut_ = debut_;
        } else {
          result.debut_ = debutBuilder_.build();
        }
        if (finBuilder_ == null) {
          result.fin_ = fin_;
        } else {
          result.fin_ = finBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Booking) {
          return mergeFrom((Booking)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Booking other) {
        if (other == Booking.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasDebut()) {
          mergeDebut(other.getDebut());
        }
        if (other.hasFin()) {
          mergeFin(other.getFin());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Booking parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Booking) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.RoomType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.RoomType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RoomType type = 1;</code>
       * @return The type.
       */
      @Override
      public RoomType getType() {
        @SuppressWarnings("deprecation")
        RoomType result = RoomType.valueOf(type_);
        return result == null ? RoomType.UNRECOGNIZED : result;
      }
      /**
       * <code>.RoomType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(RoomType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RoomType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp debut_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> debutBuilder_;
      /**
       * <code>.google.protobuf.Timestamp debut = 2;</code>
       * @return Whether the debut field is set.
       */
      public boolean hasDebut() {
        return debutBuilder_ != null || debut_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 2;</code>
       * @return The debut.
       */
      public com.google.protobuf.Timestamp getDebut() {
        if (debutBuilder_ == null) {
          return debut_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : debut_;
        } else {
          return debutBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 2;</code>
       */
      public Builder setDebut(com.google.protobuf.Timestamp value) {
        if (debutBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          debut_ = value;
          onChanged();
        } else {
          debutBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 2;</code>
       */
      public Builder setDebut(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (debutBuilder_ == null) {
          debut_ = builderForValue.build();
          onChanged();
        } else {
          debutBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 2;</code>
       */
      public Builder mergeDebut(com.google.protobuf.Timestamp value) {
        if (debutBuilder_ == null) {
          if (debut_ != null) {
            debut_ =
              com.google.protobuf.Timestamp.newBuilder(debut_).mergeFrom(value).buildPartial();
          } else {
            debut_ = value;
          }
          onChanged();
        } else {
          debutBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 2;</code>
       */
      public Builder clearDebut() {
        if (debutBuilder_ == null) {
          debut_ = null;
          onChanged();
        } else {
          debut_ = null;
          debutBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDebutBuilder() {
        
        onChanged();
        return getDebutFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDebutOrBuilder() {
        if (debutBuilder_ != null) {
          return debutBuilder_.getMessageOrBuilder();
        } else {
          return debut_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : debut_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp debut = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDebutFieldBuilder() {
        if (debutBuilder_ == null) {
          debutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDebut(),
                  getParentForChildren(),
                  isClean());
          debut_ = null;
        }
        return debutBuilder_;
      }

      private com.google.protobuf.Timestamp fin_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> finBuilder_;
      /**
       * <code>.google.protobuf.Timestamp fin = 3;</code>
       * @return Whether the fin field is set.
       */
      public boolean hasFin() {
        return finBuilder_ != null || fin_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 3;</code>
       * @return The fin.
       */
      public com.google.protobuf.Timestamp getFin() {
        if (finBuilder_ == null) {
          return fin_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : fin_;
        } else {
          return finBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 3;</code>
       */
      public Builder setFin(com.google.protobuf.Timestamp value) {
        if (finBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fin_ = value;
          onChanged();
        } else {
          finBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 3;</code>
       */
      public Builder setFin(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (finBuilder_ == null) {
          fin_ = builderForValue.build();
          onChanged();
        } else {
          finBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 3;</code>
       */
      public Builder mergeFin(com.google.protobuf.Timestamp value) {
        if (finBuilder_ == null) {
          if (fin_ != null) {
            fin_ =
              com.google.protobuf.Timestamp.newBuilder(fin_).mergeFrom(value).buildPartial();
          } else {
            fin_ = value;
          }
          onChanged();
        } else {
          finBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 3;</code>
       */
      public Builder clearFin() {
        if (finBuilder_ == null) {
          fin_ = null;
          onChanged();
        } else {
          fin_ = null;
          finBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getFinBuilder() {
        
        onChanged();
        return getFinFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getFinOrBuilder() {
        if (finBuilder_ != null) {
          return finBuilder_.getMessageOrBuilder();
        } else {
          return fin_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : fin_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp fin = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getFinFieldBuilder() {
        if (finBuilder_ == null) {
          finBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getFin(),
                  getParentForChildren(),
                  isClean());
          fin_ = null;
        }
        return finBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Booking)
    }

    // @@protoc_insertion_point(class_scope:Booking)
    private static final Booking DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Booking();
    }

    public static Booking getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Booking>
        PARSER = new com.google.protobuf.AbstractParser<Booking>() {
      @Override
      public Booking parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Booking(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Booking> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Booking> getParserForType() {
      return PARSER;
    }

    @Override
    public Booking getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Book)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *True if booked, false if not.
     * </pre>
     *
     * <code>bool bookStatus = 1;</code>
     * @return The bookStatus.
     */
    boolean getBookStatus();
  }
  /**
   * Protobuf type {@code Book}
   */
  public static final class Book extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Book)
      BookOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Book.newBuilder() to construct.
    private Book(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Book() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Book();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Book(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              bookStatus_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Hotel.internal_static_Book_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Hotel.internal_static_Book_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Book.class, Builder.class);
    }

    public static final int BOOKSTATUS_FIELD_NUMBER = 1;
    private boolean bookStatus_;
    /**
     * <pre>
     *True if booked, false if not.
     * </pre>
     *
     * <code>bool bookStatus = 1;</code>
     * @return The bookStatus.
     */
    @Override
    public boolean getBookStatus() {
      return bookStatus_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bookStatus_ != false) {
        output.writeBool(1, bookStatus_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bookStatus_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, bookStatus_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Book)) {
        return super.equals(obj);
      }
      Book other = (Book) obj;

      if (getBookStatus()
          != other.getBookStatus()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BOOKSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBookStatus());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Book parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Book parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Book parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Book parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Book parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Book parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Book parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Book parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Book parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Book parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Book parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Book parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Book prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Book}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Book)
        BookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Hotel.internal_static_Book_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Hotel.internal_static_Book_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Book.class, Builder.class);
      }

      // Construct using Hotel.Book.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        bookStatus_ = false;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Hotel.internal_static_Book_descriptor;
      }

      @Override
      public Book getDefaultInstanceForType() {
        return Book.getDefaultInstance();
      }

      @Override
      public Book build() {
        Book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Book buildPartial() {
        Book result = new Book(this);
        result.bookStatus_ = bookStatus_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Book) {
          return mergeFrom((Book)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Book other) {
        if (other == Book.getDefaultInstance()) return this;
        if (other.getBookStatus() != false) {
          setBookStatus(other.getBookStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Book parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Book) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean bookStatus_ ;
      /**
       * <pre>
       *True if booked, false if not.
       * </pre>
       *
       * <code>bool bookStatus = 1;</code>
       * @return The bookStatus.
       */
      @Override
      public boolean getBookStatus() {
        return bookStatus_;
      }
      /**
       * <pre>
       *True if booked, false if not.
       * </pre>
       *
       * <code>bool bookStatus = 1;</code>
       * @param value The bookStatus to set.
       * @return This builder for chaining.
       */
      public Builder setBookStatus(boolean value) {
        
        bookStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *True if booked, false if not.
       * </pre>
       *
       * <code>bool bookStatus = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBookStatus() {
        
        bookStatus_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Book)
    }

    // @@protoc_insertion_point(class_scope:Book)
    private static final Book DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Book();
    }

    public static Book getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Book>
        PARSER = new com.google.protobuf.AbstractParser<Book>() {
      @Override
      public Book parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Book(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Book> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Book> getParserForType() {
      return PARSER;
    }

    @Override
    public Book getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Dates_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Dates_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Booking_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Booking_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Book_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Book_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Hotel.proto\032\037google/protobuf/timestamp" +
      ".proto\"2\n\010RoomData\022\027\n\004type\030\001 \001(\0162\t.RoomT" +
      "ype\022\r\n\005price\030\002 \001(\002\"[\n\005Dates\022)\n\005debut\030\001 \001" +
      "(\0132\032.google.protobuf.Timestamp\022\'\n\003fin\030\002 " +
      "\001(\0132\032.google.protobuf.Timestamp\"v\n\007Booki" +
      "ng\022\027\n\004type\030\001 \001(\0162\t.RoomType\022)\n\005debut\030\002 \001" +
      "(\0132\032.google.protobuf.Timestamp\022\'\n\003fin\030\003 " +
      "\001(\0132\032.google.protobuf.Timestamp\"\032\n\004Book\022" +
      "\022\n\nbookStatus\030\001 \001(\010*7\n\010RoomType\022\013\n\007BASIQ" +
      "UE\020\000\022\016\n\nMIDL_GAMME\020\001\022\016\n\nHAUT_GAMME\020\0022N\n\r" +
      "BookHotelRoom\022\036\n\007GetRoom\022\006.Dates\032\t.RoomD" +
      "ata\"\000\022\035\n\010BookRoom\022\010.Booking\032\005.Book\"\000b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_RoomData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoomData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomData_descriptor,
        new String[] { "Type", "Price", });
    internal_static_Dates_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Dates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Dates_descriptor,
        new String[] { "Debut", "Fin", });
    internal_static_Booking_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Booking_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Booking_descriptor,
        new String[] { "Type", "Debut", "Fin", });
    internal_static_Book_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Book_descriptor,
        new String[] { "BookStatus", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
